

gsrpc:
  application:
    name: rpc-springboot-demo
    proxy: cglib

  provider:
    timeout: 1000
    retries: 1
    protocol: kindred
    serialization: kryo
    weight: 5
    host: 127.0.0.1
    port: 20888
    accepts: 1024

  consumer:
    timeout: 1000
    retries: 1
    loadbalance: random
    protocol: kindred
    port: -1
    serialization: kryo

  registry:
    host: 127.0.0.1
    port: 2181
    session: 5000


